project_id = "bcluoxofnwlmimowiqas"

[functions.send-whatsapp-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-product-catalog]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-ai-chat]
verify_jwt = false

[functions.flutterwave-initialize]
verify_jwt = false

[functions.flutterwave-webhook]
verify_jwt = false

[functions.flutterwave-verify]
verify_jwt = false

[functions.flutterwave-subscribe]
verify_jwt = false
