project_id = "bcluoxofnwlmimowiqas"

[functions.send-whatsapp-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-product-catalog]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-ai-chat]
verify_jwt = false

[functions.paystack-initialize]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.paystack-verify]
verify_jwt = false
